paths:
  movie:
    - /data/nas/Movies
  tv:
    - /data/nas/TV
db: mysql://root:suckballs@localhost/mediabrary
glue:
  user: Xedecimal
  pass: ransal
feeds:
  feed: http://www.seriesly.com/J4kAxDfFT1yzHaPw6P0FuIY21xZ6IiF8/feed/
player:
	trans:
    - client: /192.168.1.*/
      source: /data/nas
      target: file://///networkstorage/nas
    - client: /.*/
      source: /data/nas
      target: http://r.xedecimal.net:82/nas
